import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      {/* Page Title */}
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>

      {/* Description */}
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated by{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use the links below to navigate through all pages.
      </p>

      {/* Navigation Links */}
      <ul style={{ listStyle: "none", padding: "0" }}>
        {[
          { path: "/login", label: "Login" },
          { path: "/home1", label: "Home1" },
          { path: "/importtolldata", label: "Import Toll Data" },
          { path: "/statistics", label: "Statistics" },
          { path: "/interactivemap", label: "Interactive Map" },
          { path: "/viewdebts", label: "View Debts" },
        ].map((item, index) => (
          <li key={index} style={{ marginBottom: "10px" }}>
            <Link to={item.path} style={{ color: "#87CEFA", textDecoration: "none" }}>
              {item.label}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;